### ISSUE TITLE
Line from transparent color stay

### ISSUE THREAD

**Issue by PiotrFr** [tiaguinho/material-community-components#100]
I use color-picer on material Expansion Panel. 

When I choose transparent color
![image](https://user-images.githubusercontent.com/13883511/61932557-ff480f80-af83-11e9-8cd1-30b3044fd433.png)

and close color-picker the rot line stay.
![image](https://user-images.githubusercontent.com/13883511/61932385-91034d00-af83-11e9-9520-1027ac0d4726.png)

**Comment by PiotrFr** [comment]
@tiaguinho, sorry, I don't use your library in expansion panel anymore.

**Comment by tiaguinho** [comment]
Thanks for the reply.
