### ISSUE TITLE
Add support to disable click on color picker button

### ISSUE THREAD

**Issue by StickNitro** [tiaguinho/material-community-components#102]
**Describe the idea you have**

Could we add an option to the `mcc-color-picker` component to set the component to a `disabled` state which would disable the click event on the color picker button

For my use case I am using the color picker in a form but not bound to a form control (and have no need to be bound to a form control), I can disable the form but am unable to disable the color picker button

**Comment by aleksandar-kandzhichki** [comment]
@StickNitro For temporary solution you could try setting css style "pointer-events: none".
Kind of does the same job - stops any events on that HTML element, so the user won't be able to click it to open the panel

**Comment by tiaguinho** [comment]
@StickNitro ```disabled``` attribute is implemented on the component now.
