### ISSUE TITLE
Color picker onCancel/onClose output

### ISSUE THREAD

**Issue by aleksandar-kandzhichki** [tiaguinho/material-community-components#103]
**Describe the idea you have**

I think the color-picker component needs an @Output() or some way to signalize when the user has clicked the cancel and closed the panel.

Currently there is `clickOut`, which does the work for catching close for everything BUT the cancel - if you click cancel, this does not fire but the panel is closed, and you have no way to receive notification for it.

So maybe add @Output() onClose and then emit in this when clicked out AND when the panel is toggled with the `toggle()` function and `_isOpen === false`

**Comment by aleksandar-kandzhichki** [comment]
If you are OK with that approach and I am not missing an easy way to catch the "cancel" that already exists, I can make PR for this one

**Comment by tiaguinho** [comment]
I'll try to implement this next week.
But few free to implement if you want.
I'll be very happy to receive your contribution.

**Comment by sunitharb** [comment]
Much awaited.
