### ISSUE TITLE
Angular 9 & Ivy support

### ISSUE THREAD

**Issue by DefeninMaxime** [tiaguinho/material-community-components#107]
**Describe the bug**
The lib doesn't support build with Ivy engine. Then, `ngcc` can't transform it. The following error appears : 

```
Error: Error on worker #2: TypeError: Cannot read property 'injectorImports' of undefined
    at NgModuleDecoratorHandler.compile (C:\myPathTo\node_modules\@angular\compiler-cli\src\ngtsc\annotations\src\n
g_module.js:347:174)
```

**To Reproduce**
In project use `material-community-components`, execute: ` ngcc --properties es2015 browser module main --first-only --create-ivy-entry-points --target .\material-community-components\
`

**Expected behavior**
Be compatible with angular 9+ and Ivy

**Desktop (please complete the following information):**
 - OS: Window10

**Comment by freemanlam** [comment]
+1

**Comment by damingerdai** [comment]
angular 9 is release, so please merge

**Comment by cobaki** [comment]
Any progress on this?

**Comment by fonzzzde** [comment]
Could you let us know when this will be released? I'm using the color picker and would like to migrate to angular 9, but this component is holding it back. Thanks!

**Comment by damingerdai** [comment]
> Could you let us know when this will be released? I'm using the color picker and would like to migrate to angular 9, but this component is holding it back. Thanks!

i have created a pr being reviewing. please wait for a moment

**Comment by fonzzzde** [comment]
> i have created a pr being reviewing. please wait for a moment

Thanks a lot for your response!

**Comment by tiaguinho** [comment]
Hi guys, sorry for the delay, and thanks @damingerdai for the PR.
The new version is released!

ENJOY!
