### ISSUE TITLE
Internationalization

### ISSUE THREAD

**Issue by StickNitro** [tiaguinho/material-community-components#114]
Provide i18n support for internationalization, this could be provided similar to MatPaginator for example (https://material.angular.io/components/paginator/overview).

For the `mcc-color-picker` for example, a `MccColorPickerIntl` class is provided by the module with default `en` language values, this allows consumers to provide their own implementation of `MatColorPickerIntl` if using a language system like `ngx-translate`, etc.

**Comment by tiaguinho** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Internationalization](https://trello.com/c/re2mdDdM/6-internationalization)

**Comment by tiaguinho** [comment]
You can do this using the ```btnConfirm``` and ```btnCancel``` inputs.
example:

```html
<mcc-color-picker [btnConfirm]="YourLabel"></mcc-color-picker>
```
or
``` html
<mcc-color-picker [btnConfirm]="'YourLabel' | translate"></mcc-color-picker>
```

***In version 6.1.0 ```btnConfirm``` and ```btnCancel``` will be changed to ```btnConfirmLabel``` and ```btnCancelLabel```.***
