### ISSUE TITLE
Transparent bar for color-picker

### ISSUE THREAD

**Issue by armenstepanyan** [tiaguinho/material-community-components#116]
Add transparent option for colorpicker. In current version i can't set  opacity(RGBA) for selected color.
[Example ](http://prntscr.com/r1pmep)

**Comment by astone2014** [comment]
Looks like you can do a transparent color but there is no variable slider.

**Comment by tiaguinho** [comment]
I'm working on this.
Trying to launch in the next minor release.

**Comment by tiaguinho** [comment]
Will be available in [v7.1.0](https://github.com/tiaguinho/material-community-components/milestone/5)
