### ISSUE TITLE
Angular 9 - can't resolve 'rxjs/BehaviorSubject'

### ISSUE THREAD

**Issue by AsmisAlan** [tiaguinho/material-community-components#118]
**Describe the bug**
Hello, after installing your library and including it in one of my modules, the console throws an error related to rxjs.

**To Reproduce**
1. Install the library.
2. Import in one of your modules (in my case a shared one).
3. run the 'ng serve' command.

**Error** 
![image](https://user-images.githubusercontent.com/14351502/75637631-76bedb00-5c06-11ea-9638-61cbcc8194a5.png)

**Desktop information**
 - OS: windows 10.

**Additional context**
package json:

{
  "name": "....",
  "version": "....",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~8.2.14",
    "@angular/cdk": "~8.2.3",
    "@angular/common": "~8.2.14",
    "@angular/compiler": "~8.2.14",
    "@angular/core": "~8.2.14",
    "@angular/fire": "^6.0.0-rc.1",
    "@angular/forms": "~8.2.14",
    "@angular/material": "^8.2.3",
    "@angular/platform-browser": "~8.2.14",
    "@angular/platform-browser-dynamic": "~8.2.14",
    "@angular/router": "~8.2.14",
    "@auth0/angular-jwt": "^4.0.0",
    "angular-material": "^1.1.21",
    "firebase": "^7.8.0",
    "hammerjs": "^2.0.8",
    "mat-color-picker": "^1.4.3",
    "rxjs": "~6.4.0",
    "tslib": "^1.10.0",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.803.23",
    "@angular/cli": "~8.3.23",
    "@angular/compiler-cli": "~8.2.14",
    "@angular/language-service": "~8.2.14",
    "@types/node": "~8.9.4",
    "@types/jasmine": "~3.3.8",
    "@types/jasminewd2": "~2.0.3",
    "codelyzer": "^5.0.0",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.15.0",
    "typescript": "~3.5.3",
    "@angular-devkit/architect": "^0.900.0-0 || ^0.900.0",
    "firebase-tools": "^7.12.1",
    "fuzzy": "^0.1.3",
    "inquirer": "^6.2.2",
    "inquirer-autocomplete-prompt": "^1.0.1"
  }
}

**Comment by tiaguinho** [comment]
Hi @AsmisAlan 

Did you try to update your rxjs version?
I saw that you are using ```"rxjs": "~6.4.0"``` and material community components use ```"rxjs: "^6.5.4"```
