### ISSUE TITLE
Angular 9.1 broken

### ISSUE THREAD

**Issue by sebrojas14** [tiaguinho/material-community-components#121]
**Describe the bug**
Broken after angular 9.2 upgrade. v6.0.0

**Screenshots**
![image](https://user-images.githubusercontent.com/1771574/77694339-d98e6280-6f77-11ea-937c-bd7af04577fa.png)

**Comment by tiaguinho** [comment]
Hi @sebrojas14 
I just upgrade our demo-app to Angular 9.2 and did not have these errors.
Can you test again? But first, please remove ```node_modules``` and ```yarn.lock```.

Let me know if this fix your problem.

**Comment by sebrojas14** [comment]
9.2 or 9.1?

**Comment by tiaguinho** [comment]
Angular to 9.1, which is the lasted release.
Material to 9.2, which is the lasted release.

Which versions are you using?
