### ISSUE TITLE
request(feature:color-picker) Customizable selected color icon

### ISSUE THREAD

**Issue by motabass** [tiaguinho/material-community-components#129]
**There should be a way to use color-picker without material-icon-font loaded**
Because in our Project we do not use the Material-Icon-Font due to only using SVGs for icons it would be great if we could change the icon shown on the currently selected color in the picker to any other mat-icon using an SVG. Rigth now material icon "done" is used but shows up as "done"-text when material-icon-font is not loaded.
![image](https://user-images.githubusercontent.com/4824274/86344349-78eb8180-bc5a-11ea-8887-75c60f2faf62.png)

**Comment by tiaguinho** [comment]
Hi @motabass 
As you can see on the related commit, I implement a way to change the selected color icon.
On #133 I also implement an option to disable the selected icon.

Let me know if this solve your problem.

**Comment by motabass** [comment]
Hi @tiaguinho 

Thanks for your work. This solves our Problem by being able to disable the icon. Though it would be awesome if we could use any SVG registered in **MatIconRegistry**, not only Material-Font-Icons because we don't use the Material-Font at all.

**Comment by tiaguinho** [comment]
You can register SVG in MatIconRegistry https://material.angular.io/components/icon/overview#svg-icons.
If you do this, you can use the icon as SELECTED_COLOR_ICON.

You can test this possibility by cloning the repository and trying on the demo app.

Can you make this test?

Thank you.

**Comment by motabass** [comment]
I think it should not work with SVG the way its implemented right now. Check the SVG example here: https://material.angular.io/components/icon/examples

it uses **svgIcon**-Input for SVG. Font ligatures only work with icon fonts as statet here:
https://material.angular.io/components/icon/api#MatIcon

**Comment by motabass** [comment]
Are you looking into this or should i maybe make a pull request for the SVG-Feature?

**Comment by tiaguinho** [comment]
Please open a new issue.
I'll try to implement this feature today. 😉

**Comment by motabass** [comment]
Thats great! I opened the Issue:

https://github.com/tiaguinho/material-community-components/issues/134
