### ISSUE TITLE
Cut-off digit in color-picker RGB inputs

### ISSUE THREAD

**Issue by motabass** [tiaguinho/material-community-components#131]
**Describe the bug**
RGB input-fields cut off values with 3 digits

**Expected behavior**
All 3 digits schould be fully visible

**Screenshots**
![image](https://user-images.githubusercontent.com/4824274/86344554-afc19780-bc5a-11ea-9bb7-a9eec7810a6b.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 2004
 - Browser Chrome 83
 - Version 7.0.0

**Comment by tiaguinho** [comment]
Will be released in V6.2.0

**Comment by motabass** [comment]
Isn't 7.0.0 the latest Release?

**Comment by tiaguinho** [comment]
Yeah... Sorry
I just change the milestone name and fix my comment.
Will be released in v7.1.0
