### ISSUE TITLE
request(feature:color-picker) Support SVG registered in MatIconRegistry for selected-color-icon

### ISSUE THREAD

**Issue by motabass** [tiaguinho/material-community-components#134]
Custom icons for the selected color does not work with SVGs the way its implemented right now. 

Check the SVG example here: https://material.angular.io/components/icon/examples

mat-icon uses svgIcon-Input for SVG. Font ligatures only work with icon fonts as stated here:
https://material.angular.io/components/icon/api#MatIcon

So it would have to be
<mat-icon *ngIf="selectedColor === color; else emptyIcon" [svgIcon]="selectedIcon"></mat-icon>
to work...which would in turn not work with Font-Ligatures. Thats why there is a need for a Seperate flag i think.

**Comment by motabass** [comment]
There might also be another approach to the Problem by using a Template for the Icon like MatStepper does:

https://material.angular.io/components/stepper/overview#overriding-icons

**Comment by tiaguinho** [comment]
I implemented this as a module configuration.
Example:

```typescript
@NgModule({
    imports: [
        HttpClientModule, // need to import this module from @angular/common
        MccColorPickerModule.forRoot({
            selected_svg_icon: '/assets/images/icon.svg'
        })
    ]
})
```

This feature will be available at [v7.1.0](https://github.com/tiaguinho/material-community-components/milestone/5)

**Comment by motabass** [comment]
Hi. Can i reference an icon already registered in MatIconRegistry by name this way?

**Comment by motabass** [comment]
I opened a pull request:)

**Comment by motabass** [comment]
I also fixed missing InjectionToken for selected-color-svg-icon in the color-picker tests

**Comment by motabass** [comment]
Oh no. I just tried my implementation linked to my project and it wont work because mat-icon inside the library-template somehow does not find the named icon. I just don't get why this happens. Seems as if MccColorPickerModule has its own instance of MatIconRegistry...do you have any idea why this happens?

**Comment by motabass** [comment]
> OH NO. I just tried my implementation linked to my project and it wont work because mat-icon inside the library-template somehow does not find the named icon. I just don't get why this happens. Seems as if MccColorPickerModule has its own instance of MatIconRegistry...do you have any idea why this happens?

Seems as if the Problem came from linking the library with npm link

**Comment by motabass** [comment]
Can you link PRs https://github.com/tiaguinho/material-community-components/pull/136 and https://github.com/tiaguinho/material-community-components/pull/135 to this Issue?. I think we should then be able to close it;)
