### ISSUE TITLE
Package build is failing

### ISSUE THREAD

**Issue by motabass** [tiaguinho/material-community-components#150]
When i try to build the package using the "packgr" script from package.json on cuurent master branch i get the following error:

```
ERROR: error TS6053: File '/home/mohoritsch/WORKSPACE/material-community-components/src/lib/index.ts' not found.
src/lib/material-community-components.ts:5:15 - error TS2307: Cannot find module './index' or its corresponding type declarations.
```

![image](https://user-images.githubusercontent.com/4824274/89181680-8024e880-d594-11ea-8f11-1adc0bdee46a.png)

**Comment by tiaguinho** [comment]
I'm working on this.
