### ISSUE TITLE
Consider migrating to nx-workspace

### ISSUE THREAD

**Issue by motabass** [tiaguinho/material-community-components#152]
Did you consider using https://github.com/nrwl/nx ?

It adds great tooling on top of the angular cli and makes handling multible libraries very simple.

Maybe it would be a good idea to split the material-community-components into separate scoped npm packages like that: @mcc/color-picker, @mcc/time-picker etc.

That way you also don't have to mess around with secondary entry-points in packgr. (Though packgr is fully supported and used by nx)

On top nx adds prettier for formating, storybook and cypress support for UI component tests  and showcase-examples
, optionally jest for unit-tests and more

@tiaguinho what you think?

Alternativly i would suggest to migrate to the the standard folder layout of angular-cli with /packages folder and have only secoundary-entry-points for the different components. Because right now also users that use only time-picker will pull in **tinycolor-es** which would increase bundle sizes.

**Comment by motabass** [comment]
#85 is also talking about problems with the way all components being packaged together.

**Comment by motabass** [comment]
#150 seems to be ralted to this

**Comment by tiaguinho** [comment]
I like your idea.
My [last commit](https://github.com/tiaguinho/material-community-components/commit/ab6594eece4bc743d5df1dba9592351e40e121c3) will separate the components for the next version, but I think we maybe add NX and refactor the folder structure for version 8.

What do you think @Splaktar ?

**Comment by Splaktar** [comment]
Your last commit and work towards making each component a separate module is important.

I don't think that it's worth it to publish the modules to separate packages on NPM.

I like the idea of using Nx, but I don't think that we should make every module a separate library.

**Comment by motabass** [comment]
@tiaguinho right now there seems to be a problem with the way the lib is packaged. When i try to consume the lib built from current master i get the following error from ngcc:

**Comment by motabass** [comment]
#166

**Comment by motabass** [comment]
Why did you close this issue?
