### ISSUE TITLE
[ColorPicker] click on strict corner is difficult

### ISSUE THREAD

**Issue by DefeninMaxime** [tiaguinho/material-community-components#156]
**Describe the bug**
It's very difficult to get a color in corner of picker. For example rgb(255,255,255) at top left corner.

**To Reproduce**
1. Open color picker
2. Click on the corner left top (for example)

**Expected behavior**
I could choose a color in corner.

**Comment by motabass** [comment]
Thats still true in current master. The Problem seems to be that it's impossible to sample pure white or black from the canvas. 

I will try to fix this by some cheating;)...
