### ISSUE TITLE
Package with secondary entry-points doesn't seem to work in Angular 10

### ISSUE THREAD

**Issue by motabass** [tiaguinho/material-community-components#166]
When i use packgr to build the lib, npm pack to package it and then install it in my application with npm install ngcc throws an error in the postinstall build-script.

@tiaguinho may you please check if you experience the same problem?

**Comment by Splaktar** [comment]
What is the error?

**Comment by motabass** [comment]
When i link the lib with npm link i get the following:

` ERROR in node_modules/material-community-components/color-picker/color-picker.module.d.ts:3:22 - error NG6002: Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class.
    
    This likely means that the library (material-community-components/color-picker) which declares MccColorPickerModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.
    
    3 export declare class MccColorPickerModule {
                           ~~~~~~~~~~~~~~~~~~~~
`

**Comment by Splaktar** [comment]
Did you run `ngcc` before trying to npm link?

**Comment by motabass** [comment]
No it runs automatically after linking when i start the app. Strangely 2 days ago i was also getting an error from ngcc like 'circular dependencies in source-maps' but that seems to be gone now since i removed all exports from the primary entry point and having only secondary ones.

**Comment by motabass** [comment]
I worked out the Problem. There where just missing some exports in color-picker's public-api which caused `ngcc` to NOT compile this one entry-point. After adding these all work just fine!

BTW: Does `ngcc` have problems with a combined primary entry-point and same code in secondary entry-points at the same time?

**Comment by motabass** [comment]
fixed in #165

**Comment by motabass** [comment]
This can be closed due to having working secondary-entry-points in 9.0.0
