### ISSUE TITLE
Update demo to latest release

### ISSUE THREAD

**Issue by motabass** [tiaguinho/material-community-components#169]
Right now the demo linked in README.md is still is on 7.0.0. 

@tiaguinho coulkd you please make a new build of the demo? Or maybe do some automatic pipeline when doing a release?

**Comment by tiaguinho** [comment]
Sorry for forgetting about it.
I was a little bit sick for the last days.

Now it's updated.

Thank you!

**Comment by motabass** [comment]
Hi @tiaguinho
 hope you are doing well again.

The demo still seems to be the old one.
