### ISSUE TITLE
Demo and docs are still on version 7.0.0

### ISSUE THREAD

**Issue by motabass** [tiaguinho/material-community-components#174]
https://tiaguinho.github.io/material-community-components/

**Comment by motabass** [comment]
@tiaguinho can you please update the demo?

**Comment by tiaguinho** [comment]
@motabass the ```ng deploy``` command is not working. I'm trying to solve this.

**Comment by motabass** [comment]
@tiaguinho i fixed the deploy. seems as if i accidentially removed the architect goal when refactoring. sorry for that;)

https://github.com/tiaguinho/material-community-components/pull/179
