### ISSUE TITLE
Color picker is cut off side of page when there is not enough room.

### ISSUE THREAD

**Issue by jamesrusso** [tiaguinho/material-community-components#175]
**Describe the bug**
Color picker can get cut off in certain situations. 

**To Reproduce**
Setup a color picker and center it on screen, make the viewport smaller (like for an iphone) and you will see that the color selector is sliced off. See screenshot below.

**Expected behavior**
the overlay should not get cut off? Perhaps it should be centered on screen?

**Screenshots**

<img width="540" alt="Screen Shot 2020-09-25 at 5 49 53 PM" src="https://user-images.githubusercontent.com/682807/94318985-b0b34e00-ff57-11ea-8cda-dc9fc8f330b8.png">

**Desktop (please complete the following information):**
 - OS: Any
 - Browser : All
 - Version All

**Additional context**

Perhaps exposing some options to the underlying CDK overlay might make this less of an issue?

**Comment by motabass** [comment]
https://github.com/tiaguinho/material-community-components/issues/170

**Comment by jamesrusso** [comment]
Closed as dupe. Sorry!
