### ISSUE TITLE
Incorrect hex-input and rgb-input css?

### ISSUE THREAD

**Issue by eholman** [tiaguinho/material-community-components#176]
**Describe the bug**
Given this HTML:
```
    <mat-form-field>
      <mat-label>Enter {{name}}</mat-label>
      <mcc-color-picker hideUsedColors matSuffix mccConnectedColorPicker [mccConnectedColorPickerOrigin]="trigger"></mcc-color-picker>
      <input matInput mccColorPickerOrigin="openOnFocus" #trigger="mccColorPickerOrigin" [formControlName]="controlName"  />
    </mat-form-field>
```

Results in:
![image](https://user-images.githubusercontent.com/5081051/94554691-bca25700-025a-11eb-879f-cc066e3794a5.png)

When I override the CSS in styles.scss with this:
```
.rgb-input{
  margin-right: 1px !important;
  width: 47px !important;
}
.hex-input{
  margin-right: 10px !important;
}

.mcc-color-picker-selector-preview{
  height: 55px !important;
}
```

That results in:
![image](https://user-images.githubusercontent.com/5081051/94554919-1440c280-025b-11eb-9766-d3604f6d1512.png)

Am I doing something wrong or is the default CSS not correct?

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by motabass** [comment]
The Inputs inside the Picker should be the veriant with underline only. You maybe have configured the outline variant globaly which seems to leak into the color-picker component. 

I will taka a look at it

**Comment by eholman** [comment]
You're good! 😎 I indeed have this in the app.module:

`providers:[{provide: MAT_FORM_FIELD_DEFAULT_OPTIONS, useValue: {appearance: 'outline'}}]`

Quickly fixed, thanks!
