### ISSUE TITLE
Alpha is set to zero when transparent ist used

### ISSUE THREAD

**Issue by lkainers** [tiaguinho/material-community-components#177]
**Describe the bug**
If you use transparent color and disable the alpha selector all following colors get alpha 0

**To Reproduce**
app.module.ts
import { MccColorPickerModule } from 'material-community-components/color-picker';

imports: [
        MccColorPickerModule.forRoot({
            empty_color: 'transparent',
            used_colors: []
        }),
]

**Expected behavior**
definition of default alpha if alpha selector is not used

**Comment by lkainers** [comment]
empty_color: 'transparent' was taken from https://tiaguinho.github.io/material-community-components/color-picker.

empty_color: '' seems to work as intended

**Comment by motabass** [comment]
I see your point. But what i don't really get is the meaning of using 'transparent' as default anyway when one does not want alpha.

Wouldn't 'white' or null be a better fit for your default color?

**Comment by lkainers** [comment]
It seems that I got the documentation wrong. For me transparent meant 'no color' and it worked that way before alpha selector was introduced. My application works with empty_color: '' too.
