### ISSUE TITLE
Relax angular version to allow 5.2

### ISSUE THREAD

**Issue by PowerKiKi** [tiaguinho/material-community-components#19]
Would it be possible to relax version dependencies on angular to allow 5.0 ([as now](https://github.com/tiaguinho/mat-color-picker/blob/master/lib/package.json#L32-L40)) and also 5.2 ?

We have a project already running on angular 5.2 and adding this library install angular 5.0 side-by-side. It then trigger [that bug](https://github.com/angular/angular/issues/21925#issuecomment-364306640) and prevent compilation altogether.

**Comment by tiaguinho** [comment]
I think this is possible.

I'm working on a new release and a blog post about the changes.
After that, I'll work on your request.

**Comment by tiaguinho** [comment]
@PowerKiKi please upgrade your installation to version 2.5.6.
