### ISSUE TITLE
Color picker doesn't update when input is equal to EMPTY_COLOR

### ISSUE THREAD

**Issue by tiaguinho** [tiaguinho/material-community-components#28]
When color picker is connected to an input and the input value is equal to EMPTY_COLOR selected isn't updated.

**Comment by jpisano** [comment]
I've also noticed that when updating the input value, while the picker's selected color is updated, the selectors color isn't updated:

![selector-not-updated](https://user-images.githubusercontent.com/1324780/37354597-647cc414-26b8-11e8-93c8-8f26a935469b.gif)

Should I file this as a separate bug?
