### ISSUE TITLE
selected color not updated in preview hex and background due to bug in coerceHexaColor

### ISSUE THREAD

**Issue by p-jan** [tiaguinho/material-community-components#31]
When changing the color the RGB values get updated while changing, but the hex value and background color of the preview-div are not updated.

I fixed it locally by changing coerceHexaColor in color-picker.ts
The validity check fails on the fact that the string doesn't start with a '#'

So I added the following lines at the beginning of the function:

  if (color != null && color.charAt(0) !== '#') {
    color = `#${color}`;
  }

PS:
I'm using the picker with [hideUsedColors]="true" [hideEmptyUsedColors]="true"
in which case the buttons overlap with the preview-div.
I fixed it locally by increasing the height of .mcc-color-picker-selector-preview to 70px instead of 40px

**Comment by tiaguinho** [comment]
Hi @p-jan.
Which browser are you using?

**Comment by jpisano** [comment]
I'm seeing the same behavior.

**Comment by tiaguinho** [comment]
I had checked the behavior and also saw the bug.
The solution works, so I'm updating the package right now.

Thanks @p-jan and @jpisano !
