### ISSUE TITLE
Color picker doesn't support ARGB values (only RGB)

### ISSUE THREAD

**Issue by alexjlockwood** [tiaguinho/material-community-components#36]
Great library!

Would love to use it. However, I couldn't find a way to specify an ARGB color value (or maybe I just missed it?). Is there a way to specify the opacity of the color (similar to this library: https://github.com/brianpkelley/md-color-picker)?

**Comment by tiaguinho** [comment]
Thanks!
I'll try to release this feature until Friday.

**Comment by alexjlockwood** [comment]
This would be a really awesome feature to add if it is easy. :)

**Comment by tiaguinho** [comment]
@alexjlockwood I'm thinking how to add this feature without making the component bigger.

Do you have some idea?

**Comment by tonymartin-dev** [comment]
Is there some change about rgba support? Really interested here

**Comment by doczoidberg** [comment]
still no opacity setting?

**Comment by chriszrc** [comment]
Or even an opacity/alpha slider? I'm looking to have something like this:

<img width="239" alt="Screen Shot 2020-01-29 at 10 12 12 AM" src="https://user-images.githubusercontent.com/25695785/73368972-df214200-427f-11ea-8cb7-7a33762f5f0e.png">

**Comment by tiaguinho** [comment]
Will be available in [v7.1.0](https://github.com/tiaguinho/material-community-components/milestone/5)
