### ISSUE TITLE
bug(color-picker): can't select #ffffff

### ISSUE THREAD

**Issue by tiaguinho** [tiaguinho/material-community-components#41]
Impossible to select #ffffff option on selection area.

**Comment by ZeMeirinhos** [comment]
It's also impossible to select #FF0000
Often it sets the colour to #000000 when trying to select the colour in the very top right corner.

**Comment by motabass** [comment]
I tried to align the selection area to fit the canvas exactly in https://github.com/tiaguinho/material-community-components/pull/136/commits/08b89022c5d85e60e637993e7f72ea39fa3d9929 but it still tends to be 1 off when picking right at the border. Maybe its only fixable by tweaking the gradient inside the canvas itself?

**Comment by motabass** [comment]
> Often it sets the colour to #000000 when trying to select the colour in the very top right corner.

This should already be fixed in 08b8902
