### ISSUE TITLE
Missing documentations, Examples

### ISSUE THREAD

**Issue by Gil-Epshtain** [tiaguinho/material-community-components#51]
I'm trying to use the color-picker library after I've run the npm install command I've tried to add the MccColorPickerModule to my app.module, but the documentation doesn't specify from where should I import it. In addition, in the example page, the "view code" section is missing so I can't understand how to use the API. When I've tried to run the demo-app I've realized that the demo-app is an empty folder (only with favicon)

**Comment by tiaguinho** [comment]
@Gil-Epshtain I just add the import example inside the docs.
I'll try to add the "view code" section next week. Until then, you can check the code from the demo-app folder.

There is a folder called **components** with a file **COMPONENT-NAME-examples.component.ts** inside each component folder. You can find every example there.
