### ISSUE TITLE
Highlight the selected color 

### ISSUE THREAD

**Issue by lippomano** [tiaguinho/material-community-components#53]
I am using the minimal version of colorpicker, like you see in the image I don't have any feedback when I select some color, I can't see the selected color before confirmation.

I think is better if the user has some feedback when he clicks on some color, maybe with an highlight around the selected button or similar.
Is it possible?

![colorpicker](https://user-images.githubusercontent.com/27501745/40231061-f091d2f4-5a99-11e8-9af2-b18d6136c647.PNG)

**Comment by ccarns** [comment]
Another similiar scenario is the above configuration with hideButtons="true" ....  and in that case you may want to just close the dialog all together as if you hit the confirm button.
