### ISSUE TITLE
The position of the circle in the top rectangular area does not change when you alter the values of the RGB form controls

### ISSUE THREAD

**Issue by alexjlockwood** [tiaguinho/material-community-components#57]
When you change the value of one of the 3 RGB text fields, the background color of the color picker changes. However, the draggable circle in that top rectangular area of the color picker does not change its position to match the new color.

<img width="283" alt="screen shot 2018-05-26 at 3 39 01 pm" src="https://user-images.githubusercontent.com/1380747/40580870-c3161866-60fd-11e8-9c1b-527e7ebdcd1d.png">

**Comment by motabass** [comment]
This is also true for the base-color-picker. The picker areas never get update by input (R,G,B and Hex) value changes and also not when opening up with a color pre-set.

Enabling this would really help the usability. It may involve some calculations though to get the X and X Position from the colors RGB values. Having a fixed px size for the selection areas, like it is right now, it should be not too hard to implement.

**Comment by motabass** [comment]
Setting the slider from values 0 - 1 shold be the simplest task. To set the hue/base-color-slider one could convert the RGB to HSL and use the H-value to set the position.

**Comment by motabass** [comment]
I also found a nice resource for how to convert eg. RGB to HSL

https://css-tricks.com/converting-color-spaces-in-javascript/

**Comment by motabass** [comment]
I already got it to work. I just had to change the gradients on the selection block a little bit to fit S and L values.

I would really consider pulling in https://www.npmjs.com/package/tinycolor2 and using it's color class to keep the current color. It supports parsing all kinds of color strings as well as converting them. 

I think many feature implementations could very much profit of the convenience it offers. 

@tiaguinho what do you think?

**Comment by motabass** [comment]
https://github.com/tiaguinho/material-community-components/pull/142
