### ISSUE TITLE
Drag gestures get canceled immediately as soon as you drag the mouse outside the bounds of the color picker

### ISSUE THREAD

**Issue by alexjlockwood** [tiaguinho/material-community-components#58]
Is this avoidable somehow? It is kind of annoying that drag gestures get canceled mid-drag as soon as your mouse accidentally moves outside of the bounds of the color picker.

**Comment by rui-cruz** [comment]
Hi,

I did not try this colorpicker yet, but from my experience you should be able to listen dom move event:

```
@HostBinding('mousedown')
onMouseDown(event: MouseEvent) {
  event.stopPropagation();

  Observable.fromEvent<MouseEvent>(document, 'mousemove')
    .takeUntil(Observable.fromEvent<MouseEvent>(document, 'mouseup'))
    .subscribe(moveEvent => {
      // get globalToLocal mouse position and respective color
    });
}
```

hope it helps

**Comment by motabass** [comment]
This should be fixed in https://github.com/tiaguinho/material-community-components/pull/136/commits/08b89022c5d85e60e637993e7f72ea39fa3d9929 inside https://github.com/tiaguinho/material-community-components/pull/136
