### ISSUE TITLE
Connect color popup picker with an input

### ISSUE THREAD

**Issue by malikfaizanhaider** [tiaguinho/material-community-components#60]
color picker popup should be  connect  with an input.

**Comment by demiro** [comment]
what is the status on that? I need to open the color picker on input click... I do something like:

`<mat-form-field appearance="fill" class="full-width-field">
      <mat-icon matPrefix>palette</mat-icon>
      <mat-label>Base color</mat-label>
      <input
        matInput
        placeholder="Hex color"
        [formControl]="themeForm.controls.baseColor"
        autocomplete="off"
        mccColorPickerOrigin
        #color1="mccColorPickerOrigin"
        (click)="color1Picker.toggle();"
      />
      <div matSuffix>
        <mcc-color-picker
          #color1Picker
          mccConnectedColorPicker
          [mccConnectedColorPickerOrigin]="color1"
        ></mcc-color-picker>
      </div>
    </mat-form-field>`

which it does not work :/

**Comment by malikfaizanhaider** [comment]
> ```js
> mccColorPickerOrigin
> ```

**Comment by malikfaizanhaider** [comment]
> what is the status on that? I need to open the color picker on input click... I do something like:
> 
> ```js
> <mat-form-field appearance="fill" class="full-width-field">
>       <mat-icon matPrefix>palette</mat-icon>
>       <mat-label>Base color</mat-label>
>       <input
>         matInput
>         placeholder="Hex color"
>         [formControl]="themeForm.controls.baseColor"
>         autocomplete="off"
>         mccColorPickerOrigin
>         #color1="mccColorPickerOrigin"
>         (click)="color1Picker.toggle();"
>       />
>       <div matSuffix>
>         <mcc-color-picker
>           #color1Picker
>           mccConnectedColorPicker
>           [mccConnectedColorPickerOrigin]="color1"
>         ></mcc-color-picker>
>       </div>
>     </mat-form-field>
> ```
> 
> which it does not work :/

`<div class="form-group">
      <mcc-color-picker class="mcc-color-picker mcc-cp-small" colorPickerSelectorHeight="100" mccConnectedColorPicker [mccConnectedColorPickerOrigin]="trigger_3">
      </mcc-color-picker>
      <form novalidate [formGroup]="form">
        <input class="form-control" matInput mccColorPickerOrigin #trigger_3="mccColorPickerOrigin" formControlName="color_3" />
      </form>
    </div>`

**Comment by malikfaizanhaider** [comment]
Try this.

```
<div class="form-group">
      <mcc-color-picker class="mcc-color-picker mcc-cp-small" colorPickerSelectorHeight="100" mccConnectedColorPicker [mccConnectedColorPickerOrigin]="trigger_3">
      </mcc-color-picker>
      <form novalidate [formGroup]="form">
        <input class="form-control" matInput mccColorPickerOrigin #trigger_3="mccColorPickerOrigin" formControlName="color_3" />
      </form>
    </div>
```
