### ISSUE TITLE
Color picker open with selected color when canceled before

### ISSUE THREAD

**Issue by guschnwg** [tiaguinho/material-community-components#61]
**Describe the bug**
When I open the color picker and select some color and cancel, the color picker should (or not?) reset the color to the selected one.

**To Reproduce**
![screencast-tiaguinho github io-2018 07 12-12-51-14](https://user-images.githubusercontent.com/15526434/42644902-1ea5ce7a-85d3-11e8-8b1c-1b34a33b2e35.gif)

**Expected behavior**
When I open the color picker again the selected color should be the actually selected color, not the one I selected before and canceled.

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: Chrome
 - Version: 66.0.3359.117 (Official Build) (64-bit)

**Comment by StickNitro** [comment]
Clicking on `Cancel` also fires the `selected` event
