### ISSUE TITLE
24h format

### ISSUE THREAD

**Issue by rubenheymans** [tiaguinho/material-community-components#62]
The timepicker should have a 24h format and not just convert it.
AM/PM is confusing for European users.
![chrome-android-time](https://user-images.githubusercontent.com/2543870/42890923-569a6298-8aae-11e8-8c12-7f554abba334.png)

**Comment by Tirabuchi** [comment]
Also, convert isn't correct as you cannot get time between 00:00 and 1:00 (12 and 1 am)

![bug1](https://user-images.githubusercontent.com/46051367/57078502-b10dd200-6cee-11e9-9e0b-cb14d3c4b539.png)
