### ISSUE TITLE
Errors compiling the module (MatColorPicker) in AOT, fresh project

### ISSUE THREAD

**Issue by Rzpeg** [tiaguinho/material-community-components#63]
**Describe the bug**
The library (mat-color-picker) makes the project un-compilable in --aot compilation. 

**To Reproduce**
1. ng new testapp
2. cd testapp
3. npm install --save @angular/material
4. npm install --save @angular/cdk
5. npm install --save rxjs-compat
6. npm install --save mat-color-picker
7. edit src\app\app.module.ts and add import BrowserAnimationsModule, MatColorPickerModule
8. ng serve --aot

**Expected behavior**
Application to compile

**Actual behavior**
ERROR in Error during template compile of 'MatColorPickerModule'
  Function calls are not supported in decorators but 'ɵmakeDecorator' was called in 'NgModule'
    'NgModule' calls 'ɵmakeDecorator'.
node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.
node_modules/mat-color-picker/node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by gizellysteffanny** [comment]
I have the same problem with 6.1.1 😢

**Comment by tiaguinho** [comment]
The component name was changed to ```material-community-components```.
Please try install using:
```bash
npm install --save material-community-components
```
or
```bash
yarn add material-community-components
```

**Comment by gizellysteffanny** [comment]
@tiaguinho Thank you so much!!!
