### ISSUE TITLE
feat: support Angular Material themes

### ISSUE THREAD

**Issue by Splaktar** [tiaguinho/material-community-components#75]
**Describe the idea you have**
It would be nice if the components worked with the existing Angular Material theme that an app has defined. Currently it looks like the time picker just hard codes a `$primary` color. I did this in my library at first as well. But I just got it updated to integrate with the Angular Material theming mixins and references. You can take a look at when I needed to do [here](https://github.com/DevIntent/dev/tree/master/projects/dev#button-bar-theming-example). I'll be covering this in my talk at DevFest Florida next weekend.

Related to https://github.com/tiaguinho/material-community-components/issues/67.

Thank you for your work on this library and building on top of Angular Material!

**Comment by tiaguinho** [comment]
I'll take a look on the link and try to implement ASAP.
I'm planning to release a new version on Wednesday with this feature included.

**Comment by tiaguinho** [comment]
@Splaktar I finally take some time to implement this feature.
I'll lunch in a few hours.
Thanks for the tip in how to implement that.

**Comment by HighSoftWare96** [comment]
The Angular Material theme are working only for the TimePicker... Can this be applied also to the ColorPicker and the other components?
