### ISSUE TITLE
Tests fail after upgrading to 3.4.0

### ISSUE THREAD

**Issue by bunjiboys** [tiaguinho/material-community-components#80]
**Describe the bug**
After upgrading from 3.3.1 to 3.4.0, any component that uses the color picker now fails unit tests with the following error
```
Error: StaticInjectorError(DynamicTestModule)[MccColorPickerService -> InjectionToken used-colors]: 
  StaticInjectorError(Platform: core)[MccColorPickerService -> InjectionToken used-colors]: 
    NullInjectorError: No provider for InjectionToken used-colors!
```

**To Reproduce**
1. Have any working implementation using the mcc-color-picker, using version 3.3.1
1. Upgrade to version 3.4.0
1. Re-run tests and see them fail with the error message above.

**Expected behavior**
A minor version upgrade should never break backwards compatibility, version 3.4.0 should work without any issues, as version 3.3.1 did

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: macOS Mojave (10.14.2)
 - Browser: N/A
- Angular version 7.2.3 / Angular Material: 7.3.0

**Comment by tiaguinho** [comment]
@bunjiboys can you show how you wrote your test?

**Comment by bunjiboys** [comment]
I took a couple minutes and looked a bit more at it, and it seems that if I do the imports as
```
imports: [
    BrowserModule,
    MccColorPickerModule,
],
```
it fails wit the error listed, which is a new behavior since 3.3.1 works just fine importing the module this way. However, if I change it to
```
imports: [
    BrowserModule,
    MccColorPickerModule.forRoot({}),
],
```
it will work with 3.4.0, but the change doesn't seem to be documented and the API documentation only states that its an option to use the `forRoot` clause to set optional default values, not that its required

**Comment by tiaguinho** [comment]
@bunjiboys this is still happening in v6.0.0?
