### ISSUE TITLE
Integration with bootstrap grid.

### ISSUE THREAD

**Issue by PierrickHus** [tiaguinho/material-community-components#82]
Hi,
I encounter a graphical issue when I'm using bootstrap grid system with the mmc-color-picker.
The div with "mcc-color-picker-selector-preview" class become too small and wordings of HEX and RGB are wrapped above the "usedColorLabel".

**To Reproduce:**
**When you create the new angular project with cli, be sure you selected sass !**

1. > ng new test-app
    * Say **no** to Angular routing.
    * Say **Sass** to stylesheet format.
2. > cd test-app
3. > npm i @angular/cdk
4. > npm i @angular/material
5. > npm i material-community-components
6. > npm i --save-dev bootstrap
7. Update your angular.json file to respec the .scss files (.sass to .scss).
```
"@schematics/angular:component": {
  "style": "scss"
}
...
"styles": [
  "src/styles.scss"
],
```
8. Update your style.scss file.
```
@import '~@angular/material/theming';

// Required
@import "~bootstrap/scss/functions";
@import "~bootstrap/scss/variables";
@import "~bootstrap/scss/mixins";

// Optional
@import '~bootstrap/scss/bootstrap-grid';
@import '~bootstrap/scss/utilities';

// Include material core styles.
@include mat-core();

// Define the light theme.
$primary: mat-palette($mat-indigo);
$accent: mat-palette($mat-pink, A200, A100, A400);

$theme: mat-light-theme($primary, $accent);
@include angular-material-theme($theme);
```
9. Update yout app.module.ts file.
```
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
import { MccColorPickerModule } from 'material-community-components';
import { AppComponent } from './app.component';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    BrowserAnimationsModule,
    MccColorPickerModule.forRoot({})
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
```
10. Update your app.component.html file.
`<mcc-color-picker [overlay]="false"></mcc-color-picker>`
11. > ng serve --open

![colorpicker-issue](https://user-images.githubusercontent.com/44547558/52117774-e124d680-2614-11e9-823c-778ae0c08bd0.PNG)

**Expected behavior**
Fix the issue:
Open the "\src\lib\color-picker\color-picker-selector.component.scss" file.
Update the ".mcc-color-picker-selector-preview" class by adding this line:
`box-sizing: content-box;`

**Desktop:**
 - OS: Windows
 - Browser: Chrome
 - Version: 3.4.0

**Comment by rajkaran** [comment]
````
::ng-deep .mcc-color-picker-selector-preview{
    box-sizing: content-box;
}
````
This can be used until PR gets reviewed.
