### ISSUE TITLE
Improving 24h formatting

### ISSUE THREAD

**Issue by Enngage** [tiaguinho/material-community-components#84]
It would be nice if the 'am' and 'pm' are localizable. Or the ability to hide these when 24 hour format is enabled would be even better because it makes little sense to use these in 24h format. This woud likely require to extend the clock to full 24 items though.

**Comment by tiaguinho** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Improving 24h formatting](https://trello.com/c/U3DQrTRn/5-improving-24h-formatting)
