### ISSUE TITLE
Color text and color button inconsistent in input trigger

### ISSUE THREAD

**Issue by mfp22** [tiaguinho/material-community-components#91]
When changing color of an input, the text in the input changes but the color of the button doesn't:
<img width="282" alt="Screen Shot 2019-06-03 at 11 50 43 AM" src="https://user-images.githubusercontent.com/13700926/58823284-8d43f180-85f6-11e9-9f27-e6e9c55df31c.png">

After clicking "Confirm", they become consistent:
![image](https://user-images.githubusercontent.com/13700926/58823384-c714f800-85f6-11e9-8230-24a0d831cbc3.png)

**Comment by motabass** [comment]
fixed in 96895bbb786032021cec2ac9d9d87e140190dcca inside #142
