### ISSUE TITLE
Support Angular 8

### ISSUE THREAD

**Issue by YZahringer** [tiaguinho/material-community-components#95]
When updating Angular to version 8.0.0, the following error are generated:
`Package "material-community-components" has an incompatible peer dependency to "zone.js" (requires "^0.8.14", would install "0.9.1").`

**Comment by tiaguinho** [comment]
I just publish a new version of the package that supports Angular 8.

**Comment by YZahringer** [comment]
@tiaguinho Thank you, another dependency warning on core-js update to 3.1.4:
> npm WARN material-community-components@3.4.3 requires a peer of core-js@^2.4.1 but none is installed. You must install peer dependencies yourself.
