### ISSUE TITLE
Recent minor version requires angular 8 upgrade

### ISSUE THREAD

**Issue by mohjache** [tiaguinho/material-community-components#97]
**Describe the idea you have**
Minor version upgrade breaks Angular 7 dependencies.
Up until 3.4.1, you could use an an angular 7 application, but the most recent minor version upgrades now depend on angular 8 packages.

It would be great to clearly articulate these changes in a changleog or better yet as the dependencies against each version on the npm website

Heres an extract of my dependencies for my angular 7 application:
 "dependencies": {
    "@angular/animations": "^7.2.15",
    "@angular/cdk": "^7.3.7",
    "@angular/common": "~7.2.0",
    "@angular/compiler": "~7.2.0",
    "@angular/core": "~7.2.0",
    "@angular/forms": "~7.2.0",
    "@angular/material": "^7.3.7",
    "@angular/material-moment-adapter": "^7.3.7",
    "@angular/platform-browser": "~7.2.0",
    "@angular/platform-browser-dynamic": "~7.2.0",
    "@angular/router": "~7.2.0",
    "@okta/okta-angular": "^1.2.1",
    "core-js": "^2.5.4",
    "material-community-components": "^3.4.1",
    "moment": "^2.24.0",
    "rxjs": "~6.5.2",
    "tslib": "^1.9.0",
    "zone.js": "~0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.13.0",
    "@angular/cli": "~7.3.9",
    "@angular/compiler-cli": "~7.2.0",
    "@angular/language-service": "~7.2.0",
    "@types/node": "~8.9.4",
    "@types/jasmine": "~2.8.8",
    "@types/jasminewd2": "~2.0.3",
    "codelyzer": "~4.5.0",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~1.1.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.11.0",
    "typescript": "~3.2.2"
  }

**Comment by tiaguinho** [comment]
Sorry about that.
You application are in Angular 7 or you have updated?
