### ISSUE TITLE
After upgrade to 5.0.0. Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

### ISSUE THREAD

**Issue by PiotrFr** [tiaguinho/material-community-components#98]
**Describe the bug**
After upgrade from 3.4.3 to 5.0.0. I get "Critical dependency: require function is used in a way in which dependencies cannot be statically extracted"

**To Reproduce**
yarn upgrade material-community-components@^5.0.0
ng serve

**Expected behavior**
success

**Screenshots**
![image](https://user-images.githubusercontent.com/13883511/61115111-09e9ab80-a492-11e9-9f7c-ab5ed60d115e.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Chrome
 - Angular 8.1.1

**Comment by tiaguinho** [comment]
Which components are you using?

**Comment by PiotrFr** [comment]
only mcc-color-picker

**Comment by micksatana** [comment]
possible this line cause the error
`import { ViewEncapsulation } from '@angular/compiler/src/core';`
it should be
`import { ViewEncapsulation } from '@angular/compiler';`

**Comment by tiaguinho** [comment]
Thank you @micksatana for point this error.
@PiotrFr I have released a new version (5.0.1), can you test and give feedback?

Thanks!

**Comment by micksatana** [comment]
Tested. Confirm it's fixed on `5.0.1`.

Thank you @tiaguinho
